version: "3.8"

services:
  app:
    container_name: app-dev-calling_systems
    image: app-dev-calling_systems
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000